"""add fkSistema and fkEmpresa to rol, fkSistema to permiso

Revision ID: c926a6e86196
Revises: 
Create Date: 2026-05-24 23:35:01.695662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c926a6e86196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkSistema', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_permisos_clave'))
        batch_op.create_index(batch_op.f('ix_permisos_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_permisos_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_unique_constraint('uq_permiso_clave_sistema', ['clave', 'fkSistema'])

    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkSistema', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('fkEmpresa', sa.String(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rol_nombre'))
        batch_op.create_index(batch_op.f('ix_rol_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_rol_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_rol_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_unique_constraint('uq_rol_nombre_sistema_empresa', ['nombre', 'fkSistema', 'fkEmpresa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rol_nombre_sistema_empresa', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rol_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_rol_fkEmpresa'))
        batch_op.drop_index(batch_op.f('ix_rol_nombre'))
        batch_op.create_index(batch_op.f('ix_rol_nombre'), ['nombre'], unique=True)
        batch_op.drop_column('fkEmpresa')
        batch_op.drop_column('fkSistema')

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_permiso_clave_sistema', type_='unique')
        batch_op.drop_index(batch_op.f('ix_permisos_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_permisos_clave'))
        batch_op.create_index(batch_op.f('ix_permisos_clave'), ['clave'], unique=True)
        batch_op.drop_column('fkSistema')

    # ### end Alembic commands ###
