"""initial migration

Revision ID: 098da8273b98
Revises: 
Create Date: 2026-05-24 23:43:08.840666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098da8273b98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario_lotes',
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursal', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('fkEntradaMercancia', sa.String(length=36), nullable=False),
    sa.Column('fkEntradaMercanciaDetalle', sa.String(length=36), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cantidadOriginal', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('inventario_lotes', schema=None) as batch_op:
        batch_op.create_index('ix_inventario_lotes_empresa', ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_lotes_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_lotes_fkEntradaMercancia'), ['fkEntradaMercancia'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_lotes_fkEntradaMercanciaDetalle'), ['fkEntradaMercanciaDetalle'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_lotes_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_lotes_fkSucursal'), ['fkSucursal'], unique=False)
        batch_op.create_index('ix_inventario_lotes_sucursal_producto', ['fkSucursal', 'fkProducto'], unique=False)

    op.create_table('lista_precios',
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursal', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('fkSistema', sa.String(length=36), nullable=False),
    sa.Column('precioVenta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precioCompra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precioMayoreo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precioPromocion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vigenciaPromocion', sa.DateTime(), nullable=True),
    sa.Column('precio_modificado', sa.Boolean(), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('lista_precios', schema=None) as batch_op:
        batch_op.create_index('ix_lista_precios_empresa', ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_precios_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_precios_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_precios_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_precios_fkSucursal'), ['fkSucursal'], unique=False)
        batch_op.create_index('ix_lista_precios_promocion_vigente', ['vigenciaPromocion'], unique=False)
        batch_op.create_index('ix_lista_precios_sucursal_producto', ['fkSucursal', 'fkProducto'], unique=True)
        batch_op.create_index(batch_op.f('ix_lista_precios_vigenciaPromocion'), ['vigenciaPromocion'], unique=False)

    op.create_table('stock_sucursal',
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursal', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('stock_sucursal', schema=None) as batch_op:
        batch_op.create_index('ix_stock_empresa', ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_sucursal_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_sucursal_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_sucursal_fkSucursal'), ['fkSucursal'], unique=False)
        batch_op.create_index('ix_stock_sucursal_producto', ['fkSucursal', 'fkProducto'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sucursal', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_sucursal_producto')
        batch_op.drop_index(batch_op.f('ix_stock_sucursal_fkSucursal'))
        batch_op.drop_index(batch_op.f('ix_stock_sucursal_fkProducto'))
        batch_op.drop_index(batch_op.f('ix_stock_sucursal_fkEmpresa'))
        batch_op.drop_index('ix_stock_empresa')

    op.drop_table('stock_sucursal')
    with op.batch_alter_table('lista_precios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lista_precios_vigenciaPromocion'))
        batch_op.drop_index('ix_lista_precios_sucursal_producto')
        batch_op.drop_index('ix_lista_precios_promocion_vigente')
        batch_op.drop_index(batch_op.f('ix_lista_precios_fkSucursal'))
        batch_op.drop_index(batch_op.f('ix_lista_precios_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_lista_precios_fkProducto'))
        batch_op.drop_index(batch_op.f('ix_lista_precios_fkEmpresa'))
        batch_op.drop_index('ix_lista_precios_empresa')

    op.drop_table('lista_precios')
    with op.batch_alter_table('inventario_lotes', schema=None) as batch_op:
        batch_op.drop_index('ix_inventario_lotes_sucursal_producto')
        batch_op.drop_index(batch_op.f('ix_inventario_lotes_fkSucursal'))
        batch_op.drop_index(batch_op.f('ix_inventario_lotes_fkProducto'))
        batch_op.drop_index(batch_op.f('ix_inventario_lotes_fkEntradaMercanciaDetalle'))
        batch_op.drop_index(batch_op.f('ix_inventario_lotes_fkEntradaMercancia'))
        batch_op.drop_index(batch_op.f('ix_inventario_lotes_fkEmpresa'))
        batch_op.drop_index('ix_inventario_lotes_empresa')

    op.drop_table('inventario_lotes')
    # ### end Alembic commands ###
