"""add fkEmpresa to cargo, fkSistema to empleado and turno_sucursal

Revision ID: 17d479a46af6
Revises: 
Create Date: 2026-05-24 23:36:19.611026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d479a46af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkEmpresa', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cargo_clave'))
        batch_op.create_index(batch_op.f('ix_cargo_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_cargo_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_unique_constraint('uq_cargo_clave_empresa', ['clave', 'fkEmpresa'])

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkSistema', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_empleado_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index('ix_empleado_sistema_empresa', ['fkSistema', 'fkEmpresa'], unique=False)

    with op.batch_alter_table('turno_sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkSistema', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_turno_sucursal_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index('ix_turno_sucursal_sistema', ['fkSistema', 'fkSucursal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno_sucursal', schema=None) as batch_op:
        batch_op.drop_index('ix_turno_sucursal_sistema')
        batch_op.drop_index(batch_op.f('ix_turno_sucursal_fkSistema'))
        batch_op.drop_column('fkSistema')

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_index('ix_empleado_sistema_empresa')
        batch_op.drop_index(batch_op.f('ix_empleado_fkSistema'))
        batch_op.drop_column('fkSistema')

    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cargo_clave_empresa', type_='unique')
        batch_op.drop_index(batch_op.f('ix_cargo_fkEmpresa'))
        batch_op.drop_index(batch_op.f('ix_cargo_clave'))
        batch_op.create_index(batch_op.f('ix_cargo_clave'), ['clave'], unique=True)
        batch_op.drop_column('fkEmpresa')

    # ### end Alembic commands ###
