"""add fkSistema to empresa

Revision ID: b12f134d1a73
Revises: 
Create Date: 2026-05-24 23:33:30.996032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12f134d1a73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fkSistema', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_empresa_clave'))
        batch_op.create_index(batch_op.f('ix_empresa_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresa_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_unique_constraint('uq_empresa_clave_sistema', ['clave', 'fkSistema'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('uq_empresa_clave_sistema', type_='unique')
        batch_op.drop_index(batch_op.f('ix_empresa_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_empresa_clave'))
        batch_op.create_index(batch_op.f('ix_empresa_clave'), ['clave'], unique=True)
        batch_op.drop_column('fkSistema')

    # ### end Alembic commands ###
