"""initial migration

Revision ID: ffbb6df4ca0d
Revises: 
Create Date: 2026-05-24 23:43:57.449666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbb6df4ca0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrada_mercancia',
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('costo_subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursal', sa.String(length=36), nullable=False),
    sa.Column('fkProveedorEmpleado', sa.String(length=36), nullable=True),
    sa.Column('fkProveedorEmpresa', sa.String(length=36), nullable=True),
    sa.Column('fkSistema', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('entrada_mercancia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fkProveedorEmpleado'), ['fkProveedorEmpleado'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fkProveedorEmpresa'), ['fkProveedorEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_fkSucursal'), ['fkSucursal'], unique=False)
        batch_op.create_index('ix_entrada_mercancia_proveedor_fecha', ['fkProveedorEmpleado', 'fecha'], unique=False)
        batch_op.create_index('ix_entrada_mercancia_sucursal_fecha', ['fkSucursal', 'fecha'], unique=False)

    op.create_table('traspaso_mercancia',
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', name='tipotraspaso'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursalOrigen', sa.String(length=36), nullable=False),
    sa.Column('fkSucursalDestino', sa.String(length=36), nullable=False),
    sa.Column('fkSistema', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('traspaso_mercancia', schema=None) as batch_op:
        batch_op.create_index('ix_traspaso_destino_fecha', ['fkSucursalDestino', 'fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_fkSucursalDestino'), ['fkSucursalDestino'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_fkSucursalOrigen'), ['fkSucursalOrigen'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_tipo'), ['tipo'], unique=False)
        batch_op.create_index('ix_traspaso_origen_fecha', ['fkSucursalOrigen', 'fecha'], unique=False)

    op.create_table('venta',
    sa.Column('numero_folio', sa.Integer(), nullable=False),
    sa.Column('folio_completo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_general', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pago', sa.Enum('EFECTIVO', 'TARJETA', name='pago'), nullable=False),
    sa.Column('fkEmpresa', sa.String(length=36), nullable=False),
    sa.Column('fkSucursal', sa.String(length=36), nullable=False),
    sa.Column('fkUsuario', sa.String(length=36), nullable=False),
    sa.Column('fkSistema', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_fkEmpresa'), ['fkEmpresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_fkSistema'), ['fkSistema'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_fkSucursal'), ['fkSucursal'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_fkUsuario'), ['fkUsuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_folio_completo'), ['folio_completo'], unique=True)
        batch_op.create_index(batch_op.f('ix_venta_numero_folio'), ['numero_folio'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_pago'), ['pago'], unique=False)
        batch_op.create_index('ix_venta_sucursal_fecha', ['fkSucursal', 'fecha'], unique=False)
        batch_op.create_index('ix_venta_sucursal_folio', ['fkSucursal', 'numero_folio'], unique=True)
        batch_op.create_index('ix_venta_usuario_fecha', ['fkUsuario', 'fecha'], unique=False)

    op.create_table('entrada_mercancia_detalle',
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_costo', sa.Enum('COSTO', 'PROMOCION', 'REGALO', name='tipocosto'), nullable=False),
    sa.Column('costo_por_pieza', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_por_pieza', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fkEntradaMercancia', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.ForeignKeyConstraint(['fkEntradaMercancia'], ['entrada_mercancia.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('entrada_mercancia_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_detalle_fkEntradaMercancia'), ['fkEntradaMercancia'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_detalle_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrada_mercancia_detalle_tipo_costo'), ['tipo_costo'], unique=False)

    op.create_table('traspaso_mercancia_detalle',
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fkTraspasoMercancia', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.ForeignKeyConstraint(['fkTraspasoMercancia'], ['traspaso_mercancia.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('traspaso_mercancia_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_detalle_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_traspaso_mercancia_detalle_fkTraspasoMercancia'), ['fkTraspasoMercancia'], unique=False)

    op.create_table('venta_detalle',
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario_producto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fkVenta', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.ForeignKeyConstraint(['fkVenta'], ['venta.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_detalle_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_detalle_fkVenta'), ['fkVenta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_detalle_fkVenta'))
        batch_op.drop_index(batch_op.f('ix_venta_detalle_fkProducto'))

    op.drop_table('venta_detalle')
    with op.batch_alter_table('traspaso_mercancia_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_detalle_fkTraspasoMercancia'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_detalle_fkProducto'))

    op.drop_table('traspaso_mercancia_detalle')
    with op.batch_alter_table('entrada_mercancia_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_detalle_tipo_costo'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_detalle_fkProducto'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_detalle_fkEntradaMercancia'))

    op.drop_table('entrada_mercancia_detalle')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index('ix_venta_usuario_fecha')
        batch_op.drop_index('ix_venta_sucursal_folio')
        batch_op.drop_index('ix_venta_sucursal_fecha')
        batch_op.drop_index(batch_op.f('ix_venta_pago'))
        batch_op.drop_index(batch_op.f('ix_venta_numero_folio'))
        batch_op.drop_index(batch_op.f('ix_venta_folio_completo'))
        batch_op.drop_index(batch_op.f('ix_venta_fkUsuario'))
        batch_op.drop_index(batch_op.f('ix_venta_fkSucursal'))
        batch_op.drop_index(batch_op.f('ix_venta_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_venta_fkEmpresa'))
        batch_op.drop_index(batch_op.f('ix_venta_fecha'))

    op.drop_table('venta')
    with op.batch_alter_table('traspaso_mercancia', schema=None) as batch_op:
        batch_op.drop_index('ix_traspaso_origen_fecha')
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_tipo'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_fkSucursalOrigen'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_fkSucursalDestino'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_fkEmpresa'))
        batch_op.drop_index(batch_op.f('ix_traspaso_mercancia_fecha'))
        batch_op.drop_index('ix_traspaso_destino_fecha')

    op.drop_table('traspaso_mercancia')
    with op.batch_alter_table('entrada_mercancia', schema=None) as batch_op:
        batch_op.drop_index('ix_entrada_mercancia_sucursal_fecha')
        batch_op.drop_index('ix_entrada_mercancia_proveedor_fecha')
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fkSucursal'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fkSistema'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fkProveedorEmpresa'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fkProveedorEmpleado'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fkEmpresa'))
        batch_op.drop_index(batch_op.f('ix_entrada_mercancia_fecha'))

    op.drop_table('entrada_mercancia')
    # ### end Alembic commands ###
