"""initial migration

Revision ID: cc57583b74aa
Revises: 
Create Date: 2026-05-24 23:45:40.598037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc57583b74aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_empleado',
    sa.Column('apellidoPaterno', sa.String(length=100), nullable=False),
    sa.Column('apellidoMaterno', sa.String(length=100), nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('proveedor_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_empleado_apellidoPaterno'), ['apellidoPaterno'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_empleado_nombres'), ['nombres'], unique=False)

    op.create_table('proveedor_marca',
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('proveedor_marca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_marca_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_proveedor_marca_nombre'), ['nombre'], unique=False)

    op.create_table('proveedor_empresa',
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('fkProveedorEmpleado', sa.String(length=36), nullable=False),
    sa.Column('fkProveedorMarca', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.ForeignKeyConstraint(['fkProveedorEmpleado'], ['proveedor_empleado.oid'], ),
    sa.ForeignKeyConstraint(['fkProveedorMarca'], ['proveedor_marca.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('proveedor_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_empresa_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_proveedor_empresa_fkProveedorEmpleado'), ['fkProveedorEmpleado'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_empresa_fkProveedorMarca'), ['fkProveedorMarca'], unique=False)
        batch_op.create_index('ix_proveedor_empresa_unique', ['fkProveedorEmpleado', 'fkProveedorMarca'], unique=True)

    op.create_table('proveedor_producto',
    sa.Column('fkProveedorEmpleado', sa.String(length=36), nullable=False),
    sa.Column('fkProducto', sa.String(length=36), nullable=False),
    sa.Column('fkProveedorMarca', sa.String(length=36), nullable=False),
    sa.Column('oid', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('editado_por', sa.String(length=36), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'ELIMINADO', 'CANCELADO', name='baseobjectestatus'), nullable=False),
    sa.ForeignKeyConstraint(['fkProveedorEmpleado'], ['proveedor_empleado.oid'], ),
    sa.ForeignKeyConstraint(['fkProveedorMarca'], ['proveedor_marca.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    with op.batch_alter_table('proveedor_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_producto_fkProducto'), ['fkProducto'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_producto_fkProveedorEmpleado'), ['fkProveedorEmpleado'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedor_producto_fkProveedorMarca'), ['fkProveedorMarca'], unique=False)
        batch_op.create_index('ix_proveedor_producto_unique', ['fkProveedorEmpleado', 'fkProducto', 'fkProveedorMarca'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor_producto', schema=None) as batch_op:
        batch_op.drop_index('ix_proveedor_producto_unique')
        batch_op.drop_index(batch_op.f('ix_proveedor_producto_fkProveedorMarca'))
        batch_op.drop_index(batch_op.f('ix_proveedor_producto_fkProveedorEmpleado'))
        batch_op.drop_index(batch_op.f('ix_proveedor_producto_fkProducto'))

    op.drop_table('proveedor_producto')
    with op.batch_alter_table('proveedor_empresa', schema=None) as batch_op:
        batch_op.drop_index('ix_proveedor_empresa_unique')
        batch_op.drop_index(batch_op.f('ix_proveedor_empresa_fkProveedorMarca'))
        batch_op.drop_index(batch_op.f('ix_proveedor_empresa_fkProveedorEmpleado'))
        batch_op.drop_index(batch_op.f('ix_proveedor_empresa_clave'))

    op.drop_table('proveedor_empresa')
    with op.batch_alter_table('proveedor_marca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedor_marca_nombre'))
        batch_op.drop_index(batch_op.f('ix_proveedor_marca_clave'))

    op.drop_table('proveedor_marca')
    with op.batch_alter_table('proveedor_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedor_empleado_nombres'))
        batch_op.drop_index(batch_op.f('ix_proveedor_empleado_apellidoPaterno'))

    op.drop_table('proveedor_empleado')
    # ### end Alembic commands ###
